### ISSUE TITLE
Attribution? 

### ISSUE THREAD

**Issue by MajorTal** [surmenok/DeepSpell#1]
This kinda looks like my code?

**Comment by surmenok** [comment]
Yes, this repo is based on your code. I keep the attribution in the license. Please let me know how can I make attribution more clear.

**Comment by surmenok** [comment]
Short summary of changes I did based on your code: https://hackernoon.com/improving-deepspell-code-bdaab1c5fb7e

**Comment by surmenok** [comment]
Made it more visible in Readme file.

**Comment by MajorTal** [comment]
No problem - I'm looking forward to see how people improve it!
